// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmkzB5ZiBP54rBVE7y2_wJzq6Qrk5W_b8',
    appId: '1:962786966781:web:816fe21a9dd1144a5fd294',
    messagingSenderId: '962786966781',
    projectId: 'flutterauth-5556e',
    authDomain: 'flutterauth-5556e.firebaseapp.com',
    storageBucket: 'flutterauth-5556e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3XOB82nvTvKHDWC2u-VNJlxW8rDROOdg',
    appId: '1:962786966781:android:8fc53abc6c3ab9055fd294',
    messagingSenderId: '962786966781',
    projectId: 'flutterauth-5556e',
    storageBucket: 'flutterauth-5556e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb-o2C2SdjwLLoPTNp735udr5HDNEecIg',
    appId: '1:962786966781:ios:dbbe57decea26a6c5fd294',
    messagingSenderId: '962786966781',
    projectId: 'flutterauth-5556e',
    storageBucket: 'flutterauth-5556e.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb-o2C2SdjwLLoPTNp735udr5HDNEecIg',
    appId: '1:962786966781:ios:dbbe57decea26a6c5fd294',
    messagingSenderId: '962786966781',
    projectId: 'flutterauth-5556e',
    storageBucket: 'flutterauth-5556e.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmkzB5ZiBP54rBVE7y2_wJzq6Qrk5W_b8',
    appId: '1:962786966781:web:60661eb5557b510e5fd294',
    messagingSenderId: '962786966781',
    projectId: 'flutterauth-5556e',
    authDomain: 'flutterauth-5556e.firebaseapp.com',
    storageBucket: 'flutterauth-5556e.firebasestorage.app',
  );
}
